---
title: "Pacific DataViz Challenge 2022"
author: "Dean Marchiori"
date: "2022-10-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Setup 

Load packages and setup

```{r}
library(tidyverse)
library(janitor)
library(sf)
library(showtext)
library(patchwork)

# load custom fonts
font_add_google(name = "Staatliches", family = "Staatliches")
showtext_auto() 
```

Read in data
```{r}
# https://pacificdata.org/data/geographic_data/percentage-of-population-within-1-5-10km-coastal-buffers/resource/e9e83263-3c0b-4696-9785-ff60d1125b57

# https://pacificdata.org/data/datastore/dump/e9e83263-3c0b-4696-9785-ff60d1125b57?bom=True

pac_raw <- read_csv('https://pacificdata.org/data/datastore/dump/e9e83263-3c0b-4696-9785-ff60d1125b57?bom=True')
```

Pre-process

```{r}
pac <- pac_raw |> 
  clean_names() |> 
  select(-id) |> 
  pivot_longer(cols = starts_with('proportion'), names_to = "zone", values_to = 'value') |> 
  mutate(zone = str_remove(zone, "proportion_of_population_within_")) |> 
  mutate(n = total_population * value / 100) |> 
  mutate(zone = fct_relevel(zone, "1km", "5km"),
         co_name = fct_reorder(co_name, total_population),
         value = value/100)
```

## Chart 1: Lollipop

```{r}
p <- pac |>
  ggplot(aes(value, co_name, col = zone, size = total_population)) +
  geom_segment(aes(
    x = 0,
    xend = value,
    y = co_name,
    yend = co_name
  ), lwd = 0.1) +
  geom_point() +
  annotate(
    "rect",
    xmin = 0,
    xmax = 1,
    ymin = 21.4,
    ymax = 22.4,
    alpha = .2,
    fill = "#B1D4E0"
  ) +
  annotate(
    "rect",
    xmin = 0,
    xmax = 1,
    ymin = 2.4,
    ymax = 3.4,
    alpha = .2,
    fill = "#B1D4E0"
  ) +
  annotate(
    "rect",
    xmin = 0,
    xmax = 1,
    ymin = 13.4,
    ymax = 14.4,
    alpha = .2,
    fill = "#B1D4E0"
  ) +
  facet_wrap( ~ zone) +
  scale_x_continuous(labels = scales::percent) +
  labs(x = "Proportion of total population living within distance to coast",
       y = "") +
  theme_bw() +
  scale_color_viridis_d(
    begin = 0.4,
    end = 1,
    direction = -1,
    option = "D"
  ) +
  scale_y_discrete(labels = scales::wrap_format(25))

# Custom annotations
ann_text <- data.frame(
  value = c(.6, .75, .75),
  co_name = c("Niue", "Kiribati (Gilbert)", "Papua New Guinea"),
  lab = c(
    "Despite small population size \nNiue only has ~25% of its \npopulation within 1km of the coast",
    "119K Kiribati residents\n live within 1km of\nthe coast",
    "PNG maintains a large \npopulation across \nmountainous terrain"
  ),
  zone = factor(c("1km", "1km", "10km"),
                levels = c("1km", "5km", "10km"))
)

p1 <- p +
  geom_text(
    data = slice(ann_text, 2),
    aes(value, co_name, label = lab),
    size = 2,
    inherit.aes = F,
    colour = "white",
    nudge_y = 0.6
  ) +
  geom_text(
    data = slice(ann_text, c(1, 3)),
    aes(value, co_name, label = lab),
    size = 2,
    inherit.aes = F,
    colour = "white"
  ) +
  theme(
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.background = element_rect(colour = NA),
    legend.position = 'none',
    panel.grid = element_blank(),
    axis.title.x = element_text('Staatliches', colour = "#B1D4E0", size = 8),
    axis.text = element_text('Staatliches', colour = "#B1D4E0")
  )

```

# Chart 2: Shapefiles

PNG 
```{r}
png <- read_sf('data/data_png/PNG_adm0.shp')
png_tf <- st_transform(png, 3832) 
png_simp <- st_simplify(png_tf, dTolerance = 2000)

png_1 <- st_buffer(png_simp, -1000)
png_5 <- st_buffer(png_simp, -5000)
png_10 <- st_buffer(png_simp, -10000)

p2 <- ggplot() +
  geom_sf(data = png_simp, fill = "#FDE725FF", lwd = 0) +
  geom_sf(data = png_1, fill = "#43BF71FF", lwd = 0) +
  geom_sf(data = png_5, fill = "#2A788EFF", lwd = 0) +
  geom_sf(data = png_10, fill = "#B1D4E0", lwd = 0) +
  labs(caption = "PNG") +
  theme_void() +
  theme(plot.background = element_rect(color = NA))
```

Kiribati 

```{r}
kiri <- read_sf('data/data_kiri/KIR_adm0.shp')
kc <- st_crop(kiri, xmin = 172.7, xmax = 173.25, ymax = 1.67, ymin = 1.28)
kiri_crop_tf <- st_transform(kc, 3832)

kiri_1 <- st_buffer(kiri_crop_tf, -1000)
kiri_5 <- st_buffer(kiri_crop_tf, -5000)
kiri_10 <- st_buffer(kiri_crop_tf, -10000)

pk <- ggplot() +
  geom_sf(data = kiri_crop_tf, fill = "#FDE725FF", lwd = 0) +
  geom_sf(data = kiri_1, fill = "#43BF71FF", lwd = 0) +
  geom_sf(data = kiri_5, fill = "#2A788EFF", lwd = 0) +
  geom_sf(data = kiri_10, fill = "#B1D4E0", lwd = 0) +
  labs(caption = "Kiribati") +
  theme_void() +
  theme(plot.background = element_rect(color = NA))
```

Niue

```{r}
niue <- read_sf('data/data_nuie/NIU_adm0.shp')
niue_tf <- st_transform(niue, 3832) 

niue_1 <- st_buffer(niue_tf, -1000)
niue_5 <- st_buffer(niue_tf, -5000)
niue_10 <- st_buffer(niue_tf, -10000)

p3 <- ggplot() +
  geom_sf(data = niue_tf, fill = "#FDE725FF", lwd = 0) +
  geom_sf(data = niue_1, fill = "#43BF71FF", lwd = 0) +
  geom_sf(data = niue_5, fill = "#2A788EFF", lwd = 0) +
  geom_sf(data = niue_10, fill = "#B1D4E0", lwd = 0) +
  labs(caption = "NUIE") +
  theme_void() +
  theme(plot.background = element_rect(color = NA))
```


## Chart 3: Final Layout

```{r}
pw <- p1 | (p2 / (p3 + pk))

final <- pw +
  plot_annotation(
    title = '97% of Pacific residents are within 10km of the coast (excl. PNG)',
    subtitle = 'Including Papua New Guinea, over half the Pacific population is still within 10km of the coast and quarter are living within 1km. Some coral atoll nations such as Tokelau and Tuvalu
are entirely within 1km of the coast. Countries in the pacific region depend on the ocean for food, employment, transportation and tourism. However this proximity increases
exposure and vunerability of those who reside in Pacific nations. Of the 22 Pacific Island  Countries and Territories (PICTs), four low-lying atolls and reef islands are recognised as
the most vunerable nations in the world to sea level rise, climate and weather disasters. The key outlier is Papua New Guinea which occupies a greater land area and mountainous terrain.',
caption = 'Source: Andrew, N. L., Bright, P., de la Rua, L., Teoh, S. J., & Vickers, M. (2019). Coastal proximity of populations in 22 Pacific Island Countries and Territories. PLoS One, 14(9), e0223249.\n Data: https://pacificdata.org/data/geographic_data/percentage-of-population-within-1-5-10km-coastal-buffers\n
Dean Marchiori | @deanmarchiori'
  ) &
  theme(
    plot.title = element_text('Staatliches', colour = "#B1D4E0", size = 28),
    plot.subtitle = element_text('Staatliches', colour = "#B1D4E0"),
    axis.title = element_text('Staatliches', colour = "#B1D4E0"),
    plot.background = element_rect(fill = "#0C2D48", colour =  NA),
    text = element_text('Staatliches', colour = "#B1D4E0")
  )
```

## Render PDF Output

A4

```{r}
ggsave("output/pacific_dataviz.pdf", plot = final, device = 'pdf', width = 297, height = 210, units = "mm")
```

